#!/bin/bash

UNAME=kevinh
DIR=/home/$UNAME
# Allow java to open low numbered ports
# sudo setcap 'cap_net_bind_service=+ep' /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
cd $DIR
# Note - no longer running at PORT=80 - instead we have ngnix sit in front of us
# Turn off newrelic for now -javaagent:$DIR/newrelic/newrelic.jar
sudo -u $UNAME -b sh -c "java -Drun.mode=prod -Xmx4G  -jar $DIR/apihub-assembly-0.2.0-SNAPSHOT.jar -XX:+HeapDumpOnOutOfMemoryError -XX:OnOutOfMemoryError=\"kill -9 %p\" </dev/null 1>$DIR/out.log 2>$DIR/err.log &"
